### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [benjaminhirsch/nova-slug-field#1]
![image](https://user-images.githubusercontent.com/32259003/45428959-579b5900-b6b3-11e8-8101-240b6ef54215.png)

**Comment by benjaminhirsch** [comment]
You need to import the class in order to use ist.

-> use Benjaminhirsch\NovaSlugField\Slug;
-> use Benjaminhirsch\NovaSlugField\TextWithSlug;

**Comment by benjaminhirsch** [comment]
I've updated the readme to make it a bit clearer. :)
