### ISSUE TITLE
Enforce unique slug

### ISSUE THREAD

**Issue by kristianharmer** [benjaminhirsch/nova-slug-field#13]
Hi Benjamin,

How would I enforce unique slugs for each model? I am using 'cviebrock/eloquent-sluggable' but the unique'ability is not enforced when creating/updating from Nova!

Best regards,
K...

**Comment by benjaminhirsch** [comment]
This can be done with updateRules()  and creationRules(). See also: https://nova.laravel.com/docs/1.0/resources/validation.html
