### ISSUE TITLE
exisitng slug shouldn't auto-update

### ISSUE THREAD

**Issue by jayenne** [benjaminhirsch/nova-slug-field#14]
Once a slug has beend saved it shouldn't auto-update as this would break backlinks.
May I suggest it only writes the slug if the slug has value = ''. This way I could manually clear a slug to make it auto generate again*.

*As the slug is a required field, clearing the slug should instantly, automatically polulate it from the TextWithSlug field's value (as it can't be empty).

I also upvote the sugestion for a single field using ->parent('title') or ->from('title') as a more flexible way to get the slug value.

I also upvote the ->unique() sugestion as slugs should be unique. This could be unique to resolve uri rarther than on it's own. ..meaning i could have multiple slugs called 'foobar' if each resolve to a unique URI.

thanks for the field. best of luck with it.

**Comment by akmalelias** [comment]
You may add hideWhenUpdating() to the slug field to avoid the slug been updated.
Example:
`Slug::make('Slug')->hideWhenUpdating()`

**Comment by benjaminhirsch** [comment]
I will add an option like ->disableAutoUpdateWhenUpdating() on the Slug. So it's possbible to disable the automatic update behaviour when updating the parent field.
