### ISSUE TITLE
disableAutoUpdateWhenUpdating not working

### ISSUE THREAD

**Issue by bernhardh** [benjaminhirsch/nova-slug-field#20]
I am on nova `v2.8.0` and trying out your package.

When I use the `disableAutoUpdateWhenUpdating()` method, the slug field isn't updating at all. When I remove it, it is behaving like expected (updating the slug field also on update view)

**Comment by tomhatzer** [comment]
@bernhardh I'd say that this is expected behaviour and does exactly what the method says it does, because when you're calling the `disableAutoUpdateWhenUpdating()` method for the slug field, you are telling it to not update its value if you are editing/updating the Resource in Nova.

**Comment by bernhardh** [comment]
I am not sure, what I have changed since then or if somehing changed in nova, but it is already working as expected.

When I created this issue, the problem was, that when I used the method `disableAutoUpdateWhenUpdating()`, that it didn't update the field even on creation. But thats not the case anymore. idk why.
