### ISSUE TITLE
Looking for a new maintainer!

### ISSUE THREAD

**Issue by benjaminhirsch** [benjaminhirsch/nova-slug-field#22]
Due to the fact that I no longer activley working with Laravel as a Framework, I'm looking for someone who is willing to maintain this little project in the future. If you're interested, let me know.

**Comment by rossjcooper** [comment]
Hi, we at @razorcreations would love to take over the package if you're happy with that? 👍

**Comment by benjaminhirsch** [comment]
Hey @rossjcooper , thank you for your offering. I've already found someone und we are in the middle of a transfer of ownership. The project will be maintained by @tomhatzer in the future. :)
