### ISSUE TITLE
1.2.5 is not available via Composer

### ISSUE THREAD

**Issue by paulbeames** [benjaminhirsch/nova-slug-field#24]
Hi

Trying to install 1.2.5 via Composer and latest release is 1.2.4

Any help gratefully appreciated.

**Comment by tomhatzer** [comment]
Hi @paulbeames,
thank you for reporting this.
I've fixed this with [1.2.6](https://github.com/tomhatzer/nova-slug-field/releases/tag/1.2.6) which should be available via packagist again.

Have a great day.
