### ISSUE TITLE
Option To Show Full URL

### ISSUE THREAD

**Issue by nickpoulos** [benjaminhirsch/nova-slug-field#6]
Hey @benjaminhirsch thanks for the cool field package, short and sweet and well done 👍 

I couldn't seem figure out how to submit a feature request type Issue, so sorry in advance if this is in the wrong spot.  

I think it would be really useful/cool to add a `->showPreviewUrl($prefix)` option (or something similar) that would show a preview of the full URL, ex: https://www.yoursite.com/super-cool-slug/ underneath/to the side of the slug text box. 

Anyone else find this useful? 

Thanks again for the hard work on the package.

**Comment by benjaminhirsch** [comment]
Hey @nickpoulos! Thank you for your words and the proposal, I like it and I think this could be a handy feature for a future version, yes.  😄
