### ISSUE TITLE
Dead code.

### ISSUE THREAD

**Issue by mathieutu** [benjaminhirsch/nova-slug-field#8]
https://github.com/benjaminhirsch/nova-slug-field/blob/592fe6940758334b911fc6bdc191026ab0d6a2ba/resources/js/components/Slug/FormField.vue#L68-L72

**Comment by benjaminhirsch** [comment]
Yeah, this is a left over from an early implementation in which I used the included slug function (str_slug()) in Laravel to generate the slug instead doing it in JavaScript. Hmm I still like the idea of using the Laravel function to generate the slug even when it felt a bit laggy. Hmmm. Nethertheless, for now it's dead code and will be removed with the next update. :)
